Including CI configs and pre-commit fix
open-services-group/peribolos-as-a-service pull request #16
Opened 2022-03-24 12:52 UTC by harshad16

Including CI configs and pre-commit fix
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

As the CI are installed org level, all the CI are enabled on this repo as well
this pr is to help with the CI.
if we don't require any CI, we would have removed them from org level.
if not, this PR is required.

2022-03-24 12:52 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **harshad16** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=open-services-group%2Fperibolos-as-a-service).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/open-services-group/peribolos-as-a-service/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["harshad16"]} -->

2022-03-24 13:05 UTC, codificat requested changes
A couple of suggestions

2022-03-24 13:05 UTC, codificat commented on .prow.yaml
> +        - image: quay.io/thoth-station/thoth-precommit-py38:v0.13.0
The latest version I see [in quay](https://quay.io/repository/thoth-station/thoth-precommit-py38?tab=tags&tag=latest) is:

```suggestion
        - image: quay.io/thoth-station/thoth-precommit-py38:v0.14.3
```

2022-03-24 13:05 UTC, codificat commented on .pre-commit-config.yaml
> +      - id: trailing-whitespace
The `pre-commit-hooks` repo is duplicate, and a couple of the hooks as well:
```suggestion
      - id: detect-private-key
      - id: check-yaml
        args: [--allow-multiple-documents]
```

2022-03-29 12:43 UTC, tumido commented
@harshad16 can you please fix this PR? It's a great improvement to the CI process and I think it would help to have it merged :slightly_smiling_face:

2022-03-29 13:07 UTC, harshad16 commented
oh i somehow missed the review.
thanks.

Ready for review @codificat @tumido

2022-03-30 10:22 UTC, tumido approved these changes
/lgtm
/approve

2022-03-30 10:23 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/open-services-group/peribolos-as-a-service/pull/16#pullrequestreview-925888037" title="Approved">tumido</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=open-services-group%2Fperibolos-as-a-service).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/open-services-group/peribolos-as-a-service/blob/main/OWNERS)~~ [tumido]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-03-30 10:25 UTC, merged